logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.coyote.http11: debug #Http 요청정보 로그 남기기

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

oauth:
  kakao:
    client_id: ${CLIENT_ID}
    redirectUri: "http://localhost:8080/oauth/redirected/kakao"
    client_secret: ${CLIENT_SECRET}
    scope: "profile_nickname,profile_image"
